export { default as Layout } from './Layout/Layout.js'
export { default as Footer } from './Footer/Footer.js'
export { default as Portal } from './Portal/Portal.js'
export { default as LazyImg } from './LazyImg/LazyImg.js'
export { default as SEO } from './Seo/Seo.js'
